---
title: "Survival Analysis LAB A"
author: Kevin Ayala
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: pdf_document
---

```{r, results='hide'}
getwd()
vet.data<-read.table("/Users/kevinlorenzoayala/desktop/vets.txt")
vet.data
```
  
```{r}
#Question 1a.
vet.time<-vet.data$V1
head(vet.time)
```

```{r}  
#Question 1b. 
vet.cns<-vet.data$V2
head(vet.cns)
```

```{r}  
#Question 1c.
library("survival")
vet.surv<-Surv(vet.data$V1,vet.data$V2)
head(vet.surv)
#did not use print function becuase I did not want to print all observations. Head was used instead. 
```

```{r}  
#Question 1d.
vet.time.mean<-mean(vet.time)
vet.time.mean

#The mean of Vet.time is 121.6277, this is biased because there still exists censored data 
#during this mean estimation.
```

```{r}

#Question 1e.
sum(vet.cns)
sum(vet.time*vet.cns)
#Sums are 128 and 15632 respectiveley, this means there are 128 observed values with a status 
#1 and not 0. Of these observed values with a status of 1, their total time grouped 
#together is 15632 becuase it is thier time multiplied by 1 then added on. The observations  
#have been censored are not included because the observed time multiplied by 0 is still 0.  
```

```{r}
#Question 1f. 
mean(vet.surv)
mean(vet.cns)
# our mean is for vet.surv is 61.28, this mean has been generated by taking the average of two 
#averages for vet.cns (.9343) and (121.6277) for vet.time known as a Kaplan-Meier Estimate. 
```

```{r}
  
#Question 2a
retire <- read.table("/Users/kevinlorenzoayala/desktop/retire.txt", header=TRUE,skip=2)
head(retire)
ret.surv<-Surv(retire$time, retire$death)
head(ret.surv)
```

```{r}
#Question 2b
km.est<-survfit(ret.surv ~ 1)
km.est
```

```{r}
#Question 2c
fit1<-survfit(Surv(retire$time, retire$death) ~ 1)
plot(fit1, col ="red", xlab = "Time In Months", ylab = "s(t)", main = "Retire Survival Function")
```

```{r}
#Question 2D
summary(km.est)
#This summary tells us that at 50 months, the rate of surviving is 0.837, at 51 months the 
#survival rate drops to .835 and continues to do so till 136 months at a rate of .478

```









